#!/bin/bash

# This script is a wrapper for the jōnin build system

if ! command -v "lua" > /dev/null 2>&1; then
	echo "[Error] Lua interpreter not found."
	exit 1
fi

if ! command -v "ninja" > /dev/null 2>&1; then
	echo "[Error] Ninja build tool not found."
	exit 1
fi

JONIN_WORKING_DIRECTORY="$PWD"
export JONIN_WORKING_DIRECTORY

LIB_DIR="$(cd -- "$(dirname -- "$(readlink -f -- "$0")")" && pwd)"
LIB_MAIN="$LIB_DIR/src/main.lua"

LIB_INCL_DIR="$LIB_DIR/include"
LUA_PKG_PATH="$LIB_INCL_DIR/?.lua;$LIB_DIR/?.lua;;"

if [[ -f "$LIB_DIR/src/main.lua" ]]; then
	exec lua -e "package.path='$LUA_PKG_PATH' .. package.path" "$LIB_MAIN" "$@"
else
	echo "[Error] Failed to locate main executable."
fi

