#!/bin/sh

# This script is a wrapper for the jōnin build system. Use this instead of calling the build-options.lua script directly.

if ! command -v "lua" > /dev/null 2>&1; then
	echo "[Error] Lua interpreter not found."
	exit 1
fi

if ! command -v "ninja" > /dev/null 2>&1; then
	echo "[Error] Ninja build tool not found."
	exit 1
fi

JONIN_WORKING_DIRECTORY="$PWD"
export JONIN_WORKING_DIRECTORY

BUILD_OPTIONS="${1:-./build-options.lua}"

LIB_DIR="$(cd -- "$(dirname -- "$(readlink -f -- "$0")")" && pwd)"
LIB_INCL_DIR="$LIB_DIR/include"
LUA_PKG_PATH="$LIB_INCL_DIR/?.lua;$LIB_DIR/?.lua;;"

if [[ -f "$BUILD_OPTIONS" ]]; then
	exec lua -e "package.path='$LUA_PKG_PATH' .. package.path" "$BUILD_OPTIONS"
else
	echo "[Error] Build script '$BUILD_OPTIONS' not found."
	exit 1
fi

