#include "project.hpp"
#include <fstream>
#include <iostream>
#include <mutex>
#include <stdexcept>

namespace jonin_bt {
using namespace std;

Project *Project::instance_ = nullptr;
mutex Project::mtx;

Project::Project() {
	// These are just defaults that may be overwritten later:
	name = "Default";
	lua_script = "./.build.lua";
	build_file = "./build.ninja";
	targets = TargetMap{};
	macros = MacroMap{};
}

auto Project::instance() -> Project * {
	if (instance_ == nullptr) {
		lock_guard<mutex> lock(mtx);
		if (instance_ == nullptr) {
			instance_ = new Project();
		}
	}

	return instance_;
}

auto Project::register_Target(Target const &target) -> void {
	if (targets.contains(target.get_name()))
		throw runtime_error("A target with the name '" + target.get_name() +
		                    " is already defined for this project");
	targets.insert({target.get_name(), std::move(target)});
}

auto Project::register_Macro(Macro const &macro) -> void {
	// TODO: Allow the user to overwrite the default macros
	if (macros.contains(macro.get_name()))
		throw runtime_error("Found ambiguous definitions for macro '" +
		                    macro.get_name() + "'");
	macros.insert({macro.get_name(), macro});
}

auto Project::write_to_disk() const -> void {
	ofstream file;
	file.open(build_file);

	file << "# This Ninja build file was generated by the jonin build system "
	        "(https://github.com/inverted-tree/jonin). DO NOT EDIT THIS FILE, "
	        "all changes will be overwritten!"
	     << endl
	     << endl;
	for (auto const &target : targets) {
		auto t = target.second;
		file << "# Target '" << t.get_name() << "'" << endl;
		file << t.to_string();
	}

	file << endl << "build all: phony";
	for (auto const &target : targets)
		file << " " << target.first;

	file << endl << "default all" << endl;

	file.close();
}

} // namespace jonin_bt
